name: The Business Growth Plan Alliance
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75843
title: The Business Growth Plan Alliance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73824388-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#223c5d'
    - '#ebedef'
    - '#657b94'
    - '#000040'
    - '#c4c9cf'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
