name: The Business Growth Plan Alliance
favicon: null
layout_spectrum: 0.50419
typography_spectrum: 0.03028227319009602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2518819593824446
  lightness: 0.5537756516132504
  saturation: 0.14548596227541566
  rhythmicContrast: 0.46101995068602264
purpose: []
